<?php

namespace BoutiqueBundle\Repository;

use BoutiqueBundle\Entity\Produit; 

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	// Si j'ai des requêtes qui concernent exclusivement la table produit, et qui sont spécifiques... je vais les coder ici plutôt que de la faire dans le controller. 
	// Cela maintient un controller plus claire/générique
	
	
	// Fonction pour récupérer toutes les catégories via le queryBuilder()
	public function findAllCategorie(){
		//Nous avons besoin du manager ici pour utiliser queryBuilder()
		$em = $this -> getEntityManager();
		
		$query = $em -> createQueryBuilder();
		$query 
			-> select('p.categorie') 
			-> distinct(true) 
			-> from(Produit::class, 'p')
			-> orderBy('p.categorie', 'ASC');
		// On bâtit une requête via des fonction PHP de doctrine.
		
		return $query -> getQuery() -> getResult(); 
		// On exécute la requête et on fetch. 
	}
	
	
	// Fonction pour récupérer toutes les catégories via le createQuery()
	public function findAllCategorie2(){
		// ON a besoin du manager ici pour utiliser createQuery()
		$em = $this -> getEntityManager();
		
		$query = $em -> createQuery("SELECT DISTINCT p.categorie FROM BoutiqueBundle\Entity\Produit p ORDER BY p.categorie");	
		// On créer une requête en SQL via Doctrine	
			
		return $query -> getResult(); 
	}
}
